<template>

    <div class="modal fade" id="resetPasswordModalId" tabindex="-1" role="dialog" aria-labelledby="resetPasswordModalId"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Reset Password</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>New Password</label>
                        <div class="input-group">
                            <input :type="showPassword ? 'text' : 'password'" v-model="password" class="form-control" autocomplete="off">
                            <div class="input-group-append">
                                <button @click="togglePassword()" class="btn btn-outline-secondary btn-sm" type="button">
                                    <i class="fas fa-fw" :class="{'fa-eye': !showPassword, 'fa-eye-slash': showPassword}"></i>
                                </button>
                            </div>
                        </div>
                        <small class="form-text text-muted"><i>This is an autogenerated password suggestion</i></small>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button @click="onUpdatePassword()" type="submit" class="btn btn-warning text-white" data-dismiss="modal">Update</button>
                </div>
            </form>
        </div>
    </div>

</template>



<script setup lang="ts">
import { ref } from 'vue';
import { faker } from '@faker-js/faker';
import { authService } from '../../auth';
import { useToast } from "vue-toastification";

const props = defineProps<{
    id: string,
    username: string
}>()

const toast = useToast();

const showPassword = ref(false)

const password = ref(props.username + faker.number.int({min: 100, max: 999}))

const togglePassword = () => {
    showPassword.value = !showPassword.value
}

const onUpdatePassword = async() => {
    console.log('onSubmit()')
    const passwordUpdated = await authService.updatePassword(props.id, password.value)

    if(passwordUpdated){
        toast.success("Password updated!")
    }else{
        toast.error("Failed to update password!")
    }

}

</script>